name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: dependencies install
        run: sudo apt-get install openssl expect

      - name: Наличие README.md
        run: |
          chmod +x test.sh
          ./test.sh
  
      - name: Проверка шифрования
        run: |
          chmod +x test1.sh
          ./test1.sh
      - name: Проверка расшифровки
        run: |
          chmod +x test2.sh
          ./test2.sh
