name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Creating file.txt
        run: echo "Hello world!" > "file.txt"

      - name: openssl install
        run: sudo apt-get install openssl
        continue-on-error: true

      - name: Running the script
        run: |
          chmod +x ./dz.sh
          echo "1234
          1234" | ./dz.sh file.txt

      - name: Checking with uncorrect password
        run: |
          ./dz.sh file.txt 12345
        continue-on-error: true
  
      - name: Checking with correct password
        run: |
          ./dz.sh file.txt 1234
